### ISSUE TITLE
Emails sent from webmail do not sync to Lokole client

### ISSUE THREAD

**Issue by c-w** [ascoderu/lokole#459]
From @nzola 

> Another issue; WEB sentbox does not sink sent mail from the WEB to the BOX sentbox. It used to work.

The emails synced to the Lokole clients are temporarily stored in the Azure `pending_storage`:, e.g. see for inbound emails: https://github.com/ascoderu/lokole/blob/0b10499e9e6c147eeba775d68a5c02c1cdb798f9/opwen_email_server/actions.py#L110

This storage is also written in the webapp: https://github.com/ascoderu/lokole/blob/0b10499e9e6c147eeba775d68a5c02c1cdb798f9/opwen_email_server/integration/webapp.py#L150

Need to debug why this isn't flowing all the way through to the client.

**Comment by nzola** [comment]
I have been testing this issue again since yesterday. I have noticed:
1) Webmail sentbox sinks with Lokole client sentbox, but inconsistently. Some emails do not sink. 
2) Webmail inbox sinks with Lokole client inbox, but inconsistently. Some emails do not sink. 
I will keep on testing and give you another report on Wednesday May 20, 2020.

**Comment by adamsclafani** [comment]
@c-w Could the (deleting of pending emails)[https://github.com/ascoderu/lokole/blob/0b10499e9e6c147eeba775d68a5c02c1cdb798f9/opwen_email_server/actions.py#L319] after DownloadClientEmails is called cause the inboxes between the webmail and Lokole box to be inconsistent? For example, if emails are fetched from the web, then from the box, the pending emails don't exist anymore because they have already been fetched by the webmail?

**Comment by c-w** [comment]
@adamsclafani I don't think that's the case. The webmail doesn't use `DownloadClientEmails` and instead looks a the [sent folder](https://github.com/ascoderu/lokole/blob/5645eff1c210bee17a5ae95fe989b6ae5dba86d4/opwen_email_server/integration/webapp.py#L185-L186) which is [populated whenever a client uploads emails to the service](https://github.com/ascoderu/lokole/blob/5645eff1c210bee17a5ae95fe989b6ae5dba86d4/opwen_email_server/actions.py#L150-L156).

**Comment by sbathgate** [comment]
@nzola 
> @c-w @adamsclafani I have been testing this issue again since yesterday. I have noticed:
> 
> 1. Webmail sentbox sinks with Lokole client sentbox, but inconsistently. Some emails do not sink.
> 2. Webmail inbox sinks with Lokole client inbox, but inconsistently. Some emails do not sink.
>    I will keep on testing and give you another report on Wednesday May 20, 2020.

When you say the sync is inconsistent, is this an issue that both westest1 and westest2 occasionally do not sync? I just want to make sure this isn't related to westest2 not having it's DNS setup.

**Comment by sbathgate** [comment]
This was resolved at the same time as Issue #458 . Fault resulted from Cloudflare details not being configured.
